[project]
name = "pyfi"
version = "1.0.0"
description = "Python Fixed-point Library"
authors = [{name = "Cesar Pires Severo"}]
license = {file = "license.txt"}
readme = "readme.md"
keywords = [
  "fixed", 
  "point", 
  "fixed point", 
  "floating point", 
  "converter", 
  "fi"]
requires-python = ">= 3.10"
dependencies = []
classifiers = [
  "Development Status :: 3 - Alpha",
  "Natural Language :: English",
  "Operating System :: POSIX :: Linux",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering :: Mathematics",
  "Programming Language :: Python :: 3.10"]
[project.urls]
Repository = "https://github.com/CesarPiresSevero/pyfi" 
